package interfaces;

import clases.Metodos;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class Encriptar extends javax.swing.JFrame
{

    String textOr = "";
    int tipoEn = 0;
    int des = 0;
    boolean bdes = false;

    /**
     * Creates new form Principal
     */
    public Encriptar()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextEnc = new javax.swing.JTextArea();
        TipoEncriptado = new javax.swing.JComboBox<>();
        btnEnc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextOriginal = new javax.swing.JTextArea();
        Clave = new javax.swing.JLabel();
        Llave = new javax.swing.JLabel();
        btnDesEncriptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextEnc.setColumns(20);
        TextEnc.setLineWrap(true);
        TextEnc.setRows(5);
        jScrollPane1.setViewportView(TextEnc);

        TipoEncriptado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROT13", "Cesar", "Vigeneré" }));
        TipoEncriptado.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                TipoEncriptadoItemStateChanged(evt);
            }
        });
        TipoEncriptado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TipoEncriptadoActionPerformed(evt);
            }
        });

        btnEnc.setText("Encriptar");
        btnEnc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEncActionPerformed(evt);
            }
        });

        TextOriginal.setColumns(20);
        TextOriginal.setLineWrap(true);
        TextOriginal.setRows(5);
        jScrollPane2.setViewportView(TextOriginal);

        btnDesEncriptar.setText("DesEncriptar");
        btnDesEncriptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDesEncriptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoEncriptado, 0, 150, Short.MAX_VALUE)
                            .addComponent(Clave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Llave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDesEncriptar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(485, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TipoEncriptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Llave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(btnEnc)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesEncriptar)
                        .addGap(57, 57, 57)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TipoEncriptadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TipoEncriptadoActionPerformed
    {//GEN-HEADEREND:event_TipoEncriptadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoEncriptadoActionPerformed

    private void TipoEncriptadoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_TipoEncriptadoItemStateChanged
    {//GEN-HEADEREND:event_TipoEncriptadoItemStateChanged
        this.tipoEn = TipoEncriptado.getSelectedIndex();
        if(this.tipoEn == 1 && !bdes)
        {
            String obj =  JOptionPane.showInputDialog("De cuanto sera el desplazamiento");
            des = Integer.parseInt(obj);
            bdes = true;
        }else{
            bdes = false;
        }
        
    }//GEN-LAST:event_TipoEncriptadoItemStateChanged

    private void btnEncActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEncActionPerformed
    {//GEN-HEADEREND:event_btnEncActionPerformed
        textOr = TextOriginal.getText();
        switch (this.tipoEn)
        {
            case 0:
                TextEnc.setText(Metodos.ROT13(textOr));
                break;
            case 1:
                TextEnc.setText(Metodos.Cesar(textOr, des));
                break;
        }

    }//GEN-LAST:event_btnEncActionPerformed

    private void btnDesEncriptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDesEncriptarActionPerformed
    {//GEN-HEADEREND:event_btnDesEncriptarActionPerformed
        
        textOr = TextOriginal.getText();
        switch (this.tipoEn)
        {
            case 0:
                TextEnc.setText(Metodos.ROT13(textOr));
                break;
            case 1:
                TextEnc.setText(Metodos.Cesar(textOr, -des));
                break;
        }
        
    }//GEN-LAST:event_btnDesEncriptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Encriptar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Encriptar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Encriptar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Encriptar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Encriptar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Llave;
    private javax.swing.JTextArea TextEnc;
    private javax.swing.JTextArea TextOriginal;
    private javax.swing.JComboBox<String> TipoEncriptado;
    private javax.swing.JButton btnDesEncriptar;
    private javax.swing.JButton btnEnc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
